# -*- coding: utf-8 -*-
"""smartcart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ylqtW52YVXYalroYzaer3Dgzzp91DtN0
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("smartcart_customers.csv")

df.head()

df.shape

df.info()

df.isnull().sum()

"""## **DATA PREPROCESSING**

**1. Handling Missing Values**
"""

df["Income"] = df["Income"].fillna(df["Income"].median())
# Filling data using median values

df.head()

"""2. Feature Engineering"""

# Age
df["Age"] = 2026 - df["Year_Birth"]

df.head()

# Customer joining Days

df["Dt_Customer"] = pd.to_datetime(df["Dt_Customer"], dayfirst=True)

reference_date = df["Dt_Customer"].max()

df["Customer_Tenure_Days"] = (reference_date - df["Dt_Customer"]).dt.days

df.head()

df.columns

# Spending

df["Total_Spending"] = df["MntWines"] + df["MntFruits"] + df["MntMeatProducts"] + df["MntFishProducts"] + df["MntSweetProducts"] + df["MntGoldProds"] + df["NumDealsPurchases"]

# Children
df["Total_Children"] = df["Kidhome"] + df["Teenhome"]

df.head()

# Education

df["Education"].value_counts()

df["Education"] = df["Education"].replace({
    "Basic": "UnderGraduate", "2n Cycle": "UnderGraduate",
    "Graduation": "Graduate",
    "Master": "PostGraduate", "PhD": "PostGraduate"
})

df["Education"].value_counts()

# Martial Status


df["Marital_Status"].value_counts()

df["Living_With"] = df["Marital_Status"].replace({
    "Married": "Partner", "Together": "Partner",
    "Single": "Alone", "Divorced": "Alone","Widow": "Alone",
    "Absurd": "Alone", "YOLO": "Alone"
})

df["Living_With"].value_counts()

df.head()

"""3. Removing Columns"""

# Removing Unnecessary Columnd

cols = ["ID","Year_Birth","Marital_Status","Kidhome","Teenhome","Dt_Customer"]
Spending_cols = ["MntWines","MntFruits","MntMeatProducts","MntFishProducts","MntSweetProducts","MntGoldProds"]

cols_to_drop = cols + Spending_cols

df_cleaned = df.drop(columns = cols_to_drop)

df.shape

df_cleaned.shape

df_cleaned.head()

"""4. Outliers"""

cols = ["Income","Recency","Response","Age","Total_Spending","Total_Children"]

# Relative plots of some features pairplots
sns.pairplot(df_cleaned[cols])

# Remove Outliers

print("Data size with Outliers:" , len(df_cleaned))

df_cleaned = df_cleaned[ (df_cleaned["Age"] < 90) ]

df_cleaned = df_cleaned[ (df_cleaned["Income"] < 600000) ]


print("Data size without Outliers:" , len(df_cleaned))

"""5. Corelation of Different Features (HeatMap)"""

corr = df_cleaned.corr(numeric_only=True)

plt.figure(figsize=(8,6))

sns.heatmap(
    corr,
    annot=True,
    annot_kws={"size": 6},
    cmap = "coolwarm"
)

df_cleaned.shape

df.head()

"""6. Encoding"""

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

cat_cols = ["Education", "Living_With"]

enc_cols = ohe.fit_transform(df_cleaned[cat_cols])

enc_df = pd.DataFrame(enc_cols.toarray(), columns=ohe.get_feature_names_out(cat_cols), index = df_cleaned.index)

df_encoded =  pd.concat([df_cleaned.drop(columns=cat_cols),enc_df], axis=1)

df_encoded.shape

df_encoded.head()

"""7. **Scaling**"""

from sklearn.preprocessing import StandardScaler

X = df_encoded

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_scaled

"""8. Visualization"""

X_scaled.shape

#2D
from sklearn.decomposition import PCA

pca = PCA(n_components=3)

X_pca = pca.fit_transform(X_scaled)

# plot

plt.scatter(X_pca[:,0], X_pca[:,1])

pca.explained_variance_ratio_

#plot

fig =plt.figure(figsize =(8, 6))

ax = fig.add_subplot(111, projection='3d')

ax.scatter(X_pca[:,0], X_pca[:,1], X_pca[:,2])

ax.set_xlabel("PCA1")
ax.set_ylabel("PCA2")
ax.set_zlabel("PCA3")
ax.set_title("3d projection")

"""**Analyze K Value**

1. **Elbow Method **




"""

from sklearn.cluster import KMeans
from kneed import KneeLocator

wcss = []

for k in range(1,11):
  kmeans = KMeans(n_clusters=k, random_state=42)
  kmeans.fit_predict(X_pca)
  wcss.append(kmeans.inertia_)

knee = KneeLocator(range(1,11), wcss, curve="convex", direction="decreasing")
optimal_k = knee.elbow

print("best k =", optimal_k)

plt.plot(range(1,11), wcss, marker='o')
plt.xlabel("K")
plt.ylabel("WCSS")

"""2. Silhouette **Score**"""

from sklearn.metrics import silhouette_score

scores = []

for k in range(2,11):
  kmeans = KMeans(n_clusters=k, random_state=42)
  labels = kmeans.fit_predict(X_pca)
  score = silhouette_score(X_pca, labels)
  scores.append(score)

plt.plot(range(2,11),scores,marker='o')
plt.xlabel("K")
plt.ylabel("Silhouette Score")

# Combined plot

k_range = range(2,11)

fig, ax1 = plt.subplots(figsize=(8,6))

ax1.plot(k_range, wcss[:len(k_range)], marker='o', color = "blue")
ax1.set_xlabel("K")
ax1.set_ylabel("WCSS")

ax2 = ax1.twinx()
ax2.plot(k_range,scores[:len(k_range)], marker="x", color="red", linestyle="--")
ax2.set_ylabel("Silhouette Score")

"""**Clustering**



"""

#K_Means

kmeans = KMeans(n_clusters=4, random_state = 42)
labels_kmeans = kmeans.fit_predict(X_pca)



fig  = plt.figure(figsize=(8,6))

ax = fig.add_subplot(111, projection= '3d')

ax.scatter(X_pca[:,0], X_pca[:,1], X_pca[:,2], c=labels_kmeans)

# Agglomerative Clusterig

from sklearn.cluster import AgglomerativeClustering

agg_clf = AgglomerativeClustering(n_clusters = 4, linkage="ward")
labels_agg = agg_clf.fit_predict(X_pca)

fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111, projection="3d")
ax.scatter(X_pca[:, 0], X_pca[:, 1], X_pca[:, 2], c=labels_agg)

"""**Characterization**"""

df_cleaned.drop("labels", axis = 1)
df_cleaned["clusters"] = labels_agg

df_cleaned.head()

pal = ["red", "blue", "yellow", "green"]

sns.countplot (x=df_cleaned["clusters"], palette=pal, hue=df_cleaned["clusters"])

# Income & Spending score

sns.scatterplot(x=df_cleaned["Total_Spending"], y=df_cleaned["Income"], hue=df_cleaned["clusters"], palette=pal)

# Cluster Summary

cluster_summary = df_cleaned.groupby("clusters").mean(numeric_only=True)
print(cluster_summary)